config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :body_types
  resources :car_makes do
    resources :car_models
  end
  resources :body_types
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  resources :user_types
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/body_types_controller.rb
class BodyTypesController < ApplicationController
  before_action :set_body_type, only: %i[ show edit update destroy ]

  # GET /body_types or /body_types.json
  def index
    @body_types = BodyType.all.order(body_type: :asc)
  end

  # GET /body_types/1 or /body_types/1.json
  def show
  end

  # GET /body_types/new
  def new
    @body_type = BodyType.new
  end

  # GET /body_types/1/edit
  def edit
  end

  # POST /body_types or /body_types.json
  def create
    @body_type = BodyType.new(body_type_params)

    respond_to do |format|
      if @body_type.save
        format.html { redirect_to body_type_url(@body_type), notice: "Body type was successfully created." }
        format.json { render :show, status: :created, location: @body_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @body_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /body_types/1 or /body_types/1.json
  def update
    respond_to do |format|
      if @body_type.update(body_type_params)
        format.html { redirect_to body_type_url(@body_type), notice: "Body type was successfully updated." }
        format.json { render :show, status: :ok, location: @body_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @body_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /body_types/1 or /body_types/1.json
  def destroy
    @body_type.destroy!

    respond_to do |format|
      format.html { redirect_to body_types_url, notice: "Body type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_body_type
      @body_type = BodyType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def body_type_params
      params.require(:body_type).permit(:body_type, :car_model_id)
    end
end

app/helpers/body_types_helper.rb
module BodyTypesHelper
end

app/views/body_types/_body_type.html.erb
<div id="<%= dom_id body_type %>">
  <p>
    <strong>Body type:</strong>
    <%= body_type.body_type %>
  </p>

  <p>
    <strong>Car model:</strong>
    <%= body_type.car_model_id %>
  </p>

</div>

app/views/body_types/_form.html.erb
<%= semantic_form_for @body_type do |f| %>
  <%= f.inputs do %>
    <%= f.input :body_type, :label => "Body Type: ", :wrapper_html => { :style => "list-style-type:none;" } %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, :as => :button, :button_html => { :style => "list-style-type:none;", :class => "btn btn-primary text-capitalize" } %>
    <%= f.action :cancel, :as => :link, :link_html => { :style => "list-style-type:none;", :class => "btn btn-secondary" } %>
  <% end %>
<% end %>

app/views/body_types/edit.html.erb
<h1>Edit Body Type</h1>

<%= render 'form', body_type: @body_type %>

app/views/body_types/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Body Types</h1>
  </div>

  <div class="col-sm-6 text-end">
  <%= link_to new_body_type_path, class: 'btn btn-primary' do %>
    Add New Body Type
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Body Type</th>
      </tr>
    </thead>

    <tbody>
      <% @body_types.each do |body_type| %>
        <%= content_tag :tr, id: dom_id(body_type), class: dom_class(body_type) do %>
          <td><%= link_to body_type.body_type, body_type %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/body_types/new.html.erb
<h1>New Body Type</h1>

<%= render 'form', body_type: @body_type %>

app/views/body_types/show.html.erb
<div class="page-header">
 
  <%= link_to edit_body_type_path(@body_type), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1 class="mt-3">Body Type</h1>
</div>

<dl class="dl-horizontal">
  <dt>Body Type:</dt>
  <dd><%= @body_type.body_type %></dd>
</dl>

 <%= link_to body_types_path, class: 'btn btn-secondary' do %>
    Back To Body Types
  <% end %>