config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :body_types
  resources :car_makes do
    resources :car_models
  end
  resources :body_types
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  resources :user_types
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/user_types_controller.rb
class UserTypesController < ApplicationController
    before_action :set_user_type, only: %i[ show edit update destroy ]
    before_action :authenticate_user!
    before_action :check_user_permissions

    def index
        @user_types = UserType.all.order(name: :asc)
    end

    def show
    end

    def new
        @user_type = UserType.new
    end

    def create
        @user_type = UserType.new(user_type_params)

        respond_to do |format|
            if @user_type.save
                format.html { redirect_to user_type_url(@user_type), notice: "User Type was successfully created." }
                format.json { render :show, status: :created, location: @user_type }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @user_type.errors, status: :unprocessable_entity }
            end
        end
    end

    def edit

    end

    def update
        respond_to do |format|
            if @user_type.update(user_type_params)
              format.html { redirect_to user_type_url(@user_type), notice: "User Type was successfully updated." }
              format.json { render :show, status: :ok, location: @user_type }
            else
              format.html { render :edit, status: :unprocessable_entity }
              format.json { render json: @user_type.errors, status: :unprocessable_entity }
            end
          end
    end

    def destroy
        @user_type.destroy!

        respond_to do |format|
            format.html { redirect_to user_types_url, notice: "User Type was successfully deleted." }
            format.json { head :no_content }
        end
    end

    private

    def set_user_type
        @user_type = UserType.find(params[:id])
    end

    def user_type_params
        params.require(:user_type).permit(:name)
    end

    def check_user_permissions
        unless current_user.user_type.name == "Admin"
            redirect_to root_path, alert: "You are not authorized to edit this record."
        end
    end

end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/views/user_types/_form.html.erb
<%= form_with(model: user_type) do |f| %>

    <% if user_type.errors.any? %>
        <div style="color: red">
            <h2><%= pluralize(@user_type.errors.count, "error") %> prohibited this user type from being saved:</h2>

            <ul>
                <% @user_type.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <form>
        <div class="mb-3">
            <%= f.label "User Type:", class: "form-label text-capitalize" %>
            <%= f.text_field :name, class: "form-control" %>
        </div>

        <% if user_type.persisted? %>
            <div class="float-end mb-3">
                <%= link_to 'Destroy', user_type, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>
            </div>
        <% end %>

        <div class="mb-3">
            <%= f.submit "Save", class: "btn btn-primary" %>
            <%= link_to "Cancel", user_types_path, class: "btn btn-secondary" %>
        </div>
    </form>
<% end %>

app/views/user_types/edit.html.erb
<h3>User Type</h3>

<%= render 'form', user_type: @user_type %>

app/views/user_types/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h3>User Types</h3>
  </div>

  <div class="col-sm-6 text-end">
    <%= link_to new_user_type_path, class: 'btn btn-primary' do %>
        Add New User Type
    <% end %>
  </div>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>User Type</th>
            </tr>
        </thead>
        <tbody>
             <% @user_types.each do |user_type| %>
                <%= content_tag :tr, id: dom_id(user_type), class: dom_class(user_type) do %>
                    <td><%= link_to user_type.name, user_type %></td>
                <% end %>
             <% end %>
        </tbody>
    </table>
</div>

app/views/user_types/new.html.erb
<h3>User Type</h3>
<%= render 'form', user_type: @user_type %>

app/views/user_types/show.html.erb
<div class="page-header">
  <%= link_to edit_user_type_path(@user_type), class: 'btn btn-primary' do %>
    Edit
  <% end %>
</div>

<h3 class="mt-3">User Type</h3>

<dl class="dl-horizontal mt-3">
  <dt>User Type:</dt>
  <dd><%= @user_type.name %></dd>
</dl>

<%= link_to user_types_path, class: 'btn btn-secondary' do %>
    Back to All User Types
<% end %>