config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :body_types
  resources :car_makes do
    resources :car_models
  end
  resources :body_types
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  resources :user_types
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :car_make
  belongs_to :body_type
end

app/controllers/car_models_controller.rb
class CarModelsController < ApplicationController
  before_action :set_car_model, only: %i[ show edit update destroy ]

  # GET /car_models or /car_models.json
  def index
    @car_models = CarModel.all
  end

  # GET /car_models/1 or /car_models/1.json
  def show
  end

  # GET /car_models/new
  def new
    @car_model = CarModel.new
  end

  # GET /car_models/1/edit
  def edit
  end

  # POST /car_models or /car_models.json
  def create
    @car_model = CarModel.new(car_model_params)

    respond_to do |format|
      if @car_model.save
        format.html { redirect_to car_model_url(@car_model), notice: "Car model was successfully created." }
        format.json { render :show, status: :created, location: @car_model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_models/1 or /car_models/1.json
  def update
    respond_to do |format|
      if @car_model.update(car_model_params)
        format.html { redirect_to car_model_url(@car_model), notice: "Car model was successfully updated." }
        format.json { render :show, status: :ok, location: @car_model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_models/1 or /car_models/1.json
  def destroy
    @car_model.destroy!

    respond_to do |format|
      format.html { redirect_to car_models_url, notice: "Car model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_model
      @car_model = CarModel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_model_params
      params.require(:car_model).permit(:model, :car_make_id, :body_type_id)
    end
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/views/car_models/_car_model.html.erb
<div id="<%= dom_id car_model %>">
  <p>
    <strong>Model:</strong>
    <%= car_model.model %>
  </p>

  <p>
    <strong>Make:</strong>
    <%= car_model.car_make_id %>
  </p>

</div>

app/views/car_models/_form.html.erb
<%= form_with(model: car_model) do |form| %>
  <% if car_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car_model.errors.count, "error") %> prohibited this car_model from being saved:</h2>

      <ul>
      <% car_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label "Make", class: 'form-label text-capitalize' %>
    <%= form.collection_select :car_make_id, CarMake.all.order(make: :asc), :id, :make, { }, { class: "form-control" } %>
  </div>

  <div class="mb-3">
    <%= form.label :model, class: 'form-label' %>
    <%= form.text_field :model, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :body_type_id, class: 'form-label text-capitalize' %>
    <%= form.collection_select :body_type_id, BodyType.all.order(body_type: :asc), :id, :body_type, { }, { class: "form-control" } %>
  </div>

  <div class="mb-3">
    <% if car_model.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', car_model, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary text-capitalize' %>

    <% if car_model.persisted? %>
      <%= link_to "Cancel", car_model, class: "btn btn-secondary" %>
    <% else %>
      <%= link_to "Cancel", car_models_path, class: "btn btn-secondary" %>
    <% end %>
  </div>
<% end %>

app/views/car_models/edit.html.erb
<h1>Edit Model</h1>

<%= render 'form', car_model: @car_model %>

app/views/car_models/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Car Models</h1>
  </div>

  <div class="col-sm-6 text-end">
  <%= link_to new_car_model_path, class: 'btn btn-primary' do %>
    Add New Car Model
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Model</th>
        <th>Car Make</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @car_models.each do |car_model| %>
        <%= content_tag :tr, id: dom_id(car_model), class: dom_class(car_model) do %>
          

                      <td><%= car_model.model %></td>
                      <td><%= car_model.car_make.make %></td>
          
          
            <td><%= link_to 'Show', car_model %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/car_models/new.html.erb
<h1>New Car Model</h1>

<%= render 'form', car_model: @car_model %>

app/views/car_models/show.html.erb
<div class="page-header">
  <%= link_to car_models_path, class: 'btn btn-secondary' do %>
    All Models
  <% end %>
  <%= link_to edit_car_model_path(@car_model), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1 class="mt-3">Model</h1>
</div>

<dl class="dl-horizontal">
  <dt>Make:</dt>
  <dd><%= @car_model.car_make.make %></dd>
  <dt>Model:</dt>
  <dd><%= @car_model.model %></dd>
  <dt>Body Type:</dt>
  <dd><%= @car_model.body_type.body_type %></dd>
</dl>